### ISSUE TITLE
add support for cram files

### ISSUE THREAD

**Issue by flokraft85** [PacificBiosciences/paraphase#21]
Hi,
first of all, paraphase is a really good tool!
It would be great if paraphase could accept cram files as input. 

Best,
Florian

**Comment by xiao-chen-xc** [comment]
Hi @flokraft85 yes we can do that in the next release.

**Comment by flokraft85** [comment]
Hi @xiao-chen-xc ,
that is fantastic! Thanka a lot.

**Comment by xiao-chen-xc** [comment]
Hi @flokraft85 Version 3.2 is released and it can support cram files as input.

**Comment by flokraft85** [comment]
Hi @xiao-chen-xc ,
thant is really great! Thanks for adding this feature!

**Comment by flokraft85** [comment]
Hi @xiao-chen-xc,
I tried to run paraphase with the cram, however I got some errors related to a missing ref fasta.

```python
[E::fai_build3_core] Failed to open the file /data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa
[E::refs_load_fai] Failed to open reference file '/data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa'
[W::cram_get_ref] Failed to populate reference for id 20
[E::cram_next_slice] Failure to decode slice
ERROR:root:Error running ICOSLG for sample sample1...See error message below
Traceback (most recent call last):
  File "/home/humgen/miniconda3/envs/paraphase/lib/python3.10/site-packages/paraphase/paraphase.py", line 148, in process_gene
    bam_realigner.write_realign_bam()
  File "/home/humgen/miniconda3/envs/paraphase/lib/python3.10/site-packages/paraphase/prepare_bam_and_vcf.py", line 102, in write_realign_bam
    for read in wgs.fetch(
  File "pysam/libcalignmentfile.pyx", line 2109, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
``` 
So yes, the ref fasta file is not under this path "/data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa" because this is the nextflow work tmp dir.
However, I specified the ref fasta with the -r option. Is there annother option I have to use, to specify the ref fasta for cram files?

paraphase -b input.cram -o output/paraphase -r ref.fasta -t 40

Thanks in advance!

Best Florian

**Comment by flokraft85** [comment]
Hi @xiao-chen-xc ,
There may still be an issue with how Paraphase handles CRAM files when the location of the reference file (ref.fa) changes relative to the alignment. We run our analysis using a nextflow workflow, meaning that the path to the ref.fa in the CRAM file header points only to the temporary nextflow directory. (/data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa).

```python
[E::fai_build3_core] Failed to open the file /data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa
[E::refs_load_fai] Failed to open reference file '/data/work/f7/211d11635b0faded38905bab69fdc7/GRCh38_no_alt_analysis_set_dup_masked.fa'
[W::cram_get_ref] Failed to populate reference for id 22
[E::cram_next_slice] Failure to decode slice
ERROR:root:Error running MAGEH1 for sample M34497_1...See error message below
Traceback (most recent call last):
  File "/home/humgen/miniconda3/envs/paraphase/lib/python3.10/site-packages/paraphase/paraphase.py", line 148, in process_gene
    bam_realigner.write_realign_bam()
  File "/home/humgen/miniconda3/envs/paraphase/lib/python3.10/site-packages/paraphase/prepare_bam_and_vcf.py", line 102, in write_realign_bam
    for read in wgs.fetch(
  File "pysam/libcalignmentfile.pyx", line 2109, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
``` 

Hence, paraphase may not have used the ref.fa provided with the "-r" option.

`paraphase -b input.cram -o output/paraphase -r ref.fa} -t 40`

Best,
FLorian

**Comment by xiao-chen-xc** [comment]
Hi Florian, 

I made some updates. Could you try downloading [paraphase-3.2.1a0.tar.gz](https://github.com/user-attachments/files/18649902/paraphase-3.2.1a0.tar.gz) and install it with `pip install paraphase-3.2.1a0.tar.gz`? Let me know if this version works in your workflow. 

Thanks,
Xiao

**Comment by flokraft85** [comment]
Hi Xiao,
thanks for the fixing the issue so fast. I tested the 3.2.1 alpha and now everthing works fine!

Best,
Florian

**Comment by xiao-chen-xc** [comment]
Great! I'll release v3.2.1 soon.
